apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationset
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/namespace-install
    repoURL: 'https://github.com/argoproj-labs/applicationset.git'
    targetRevision: HEAD
  project: argo
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
